import os
import sys
import pandas as pd

include: "rules/common.smk"

SAMPLES = list(samples['sample'])
base_dir = config['base_dir']

include: "rules/qc.smk"
include: "rules/align.smk"
include: "rules/filter.smk"

#running Snakemake dry run with following command, remove -n to run job:
#snakemake --cores 1 --use-envmodules -n --use-singularity --singularity-args '-B /data/millerv2'

rule all:
    input:
        expand(os.path.join(base_dir,"fastqc_raw","{sample}_fastqc.html"),sample=SAMPLES),
        expand(os.path.join(base_dir,"fastqc_raw","{sample}_fastqc.zip"),sample=SAMPLES),
        expand(os.path.join(base_dir,"trimmed_reads","{sample}_trimmed.fastq"),sample=SAMPLES),
        os.path.join(base_dir,"Nanoplot","NanoPlot-report.html"),
        expand(os.path.join(base_dir,"fastqc_trimmed","{sample}_trimmed_fastqc.html"),sample=SAMPLES),
        expand(os.path.join(base_dir,"fastqc_trimmed","{sample}_trimmed_fastqc.zip"),sample=SAMPLES),
        expand(os.path.join(base_dir,"genome_alignmments","{sample}_alignment.sam"),sample=SAMPLES)

        

