# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
samples: "/data/millerv2/NanoseqSnakemake/config/samples.tsv"

base_dir: "/data/millerv2"

sample_dir: "/data/millerv2/NanoseqSnakemake/.tests"

headcrop: 10

length: 500

genome_fasta: "/data/millerv2/genomes/genome.fa"

genome_gtf: "/data/millerv2/genomes/genes.gtf"